[server]
bind_address = "0.0.0.0"
port = 8080
websocket_port = 8081
max_connections = 1000
heartbeat_interval = 30

[authentication]
enabled = true
jwt_secret = "test-jwt-secret-key-for-e2e-testing"
session_timeout = 3600  # 1 hour

[logging]
level = "debug"
format = "json"

[routing]
enable_load_balancing = true
timeout_seconds = 30
retry_attempts = 3

[security]
enable_tls = false  # Disabled for local testing
cors_origins = ["*"]

[performance]
max_message_size = 10485760  # 10MB
compression = true
keep_alive = true

[monitoring]
enable_metrics = true
metrics_port = 8082
health_check_port = 8080
