# RemoteFS Relay High Availability Configuration
# Production-ready configuration with security, monitoring, and failover

[server]
server_id = "relay-prod-1"
bind_address = "0.0.0.0"
port = 443  # Use standard HTTPS port
max_connections = 5000
connection_timeout = 600

[server.tls]
enabled = true
cert_file = "/etc/ssl/certs/remotefs-relay.crt"
key_file = "/etc/ssl/private/remotefs-relay.key"
min_version = "1.3"

[routing]
default_strategy = "weighted"
health_check_interval = 15
max_failed_health_checks = 2
sticky_sessions = true
session_timeout = 7200

[authentication]
enabled = true
method = "token"

[authentication.token]
secret_key = "${RELAY_AUTH_SECRET}"  # Use environment variable
expiration = 3600
allow_refresh = true

[logging]
level = "info"
format = "json"
file_path = "/var/log/remotefs/relay.log"
log_requests = true
log_metrics = true

[metrics]
enabled = true
bind_address = "0.0.0.0"
port = 9091
endpoint = "/metrics"
detailed_metrics = true

[agents]
discovery_method = "consul"

[agents.consul]
address = "127.0.0.1:8500"
service_name = "remotefs-agent"
datacenter = "production"
require_passing = true
interval = 15

# Fallback static agents if Consul is unavailable
[[agents.static]]
id = "primary-agent-1"
address = "10.0.1.10:8080"
weight = 20
enabled = true
[agents.static.metadata]
region = "us-east-1"
zone = "us-east-1a"
tier = "primary"

[[agents.static]]
id = "primary-agent-2"
address = "10.0.1.11:8080"
weight = 20
enabled = true
[agents.static.metadata]
region = "us-east-1"
zone = "us-east-1b"
tier = "primary"

[[agents.static]]
id = "backup-agent-1"
address = "10.0.2.10:8080"
weight = 10
enabled = true
[agents.static.metadata]
region = "us-west-2"
zone = "us-west-2a"
tier = "backup"

[load_balancing.circuit_breaker]
enabled = true
failure_threshold = 3
recovery_timeout = 30
half_open_limit = 5

[load_balancing.rate_limit]
enabled = true
requests_per_second = 1000
burst_size = 2000

[storage]
type = "redis"

[storage.redis]
address = "redis-cluster.internal:6379"
database = 0
password = "${REDIS_PASSWORD}"
max_connections = 20
idle_timeout = 600

[performance]
worker_threads = 0  # Auto-detect
max_blocking_threads = 32
tcp_nodelay = true
tcp_keepalive = true
keepalive_idle = 300
keepalive_interval = 30
keepalive_count = 6
